variable "region" {}
variable "domain" {}
variable "dashed_domain" {}
variable "cmsdomain" {}
variable "dashed_cmsdomain" {}
variable "front_instance_count" {}
variable "strapi_instance_count" {}
variable "subnets" {}
variable "strapi_alb_tg" {}
variable "front_alb_tg" {}
variable "service_sg" {}