#!/bin/bash
export DGPATH=$(dirname $(realpath /usr/local/bin/dg))
source $DGPATH/_scripts/functions.sh

showHelp() {
    printf "${NC}$(basename "$0") [-h] [ d db dbl drb drbl r f cms tf] -- cli to manage dgrebb.com\n
    -h                      show this help text
    cms                     interact with strapi sans docker
    f | front               frontend run/build commands
    d | dev                 run strapi in development mode outside of docker
    db | dbuild             build docker images for aws
    dbl | dbuildlocal       build docker images to run locally
    drb | drebuild          rebuild docker images for aws
    drbl                    rebuild docker images to run locally
    dp                      push docker image
    r | run                 run local docker image
    tf                      run terraform commands
    \n\n"
}

if [ "$(exec sh -c 'echo "$PPID"')" != "$$" ]; then
    echo "Running dg subshell..."
else
    hello
fi

while test "$1" != --; do
    case $1 in
    c | cms)
        /bin/bash $DGPATH/_scripts/cms.sh $2 $3
        break
        ;;
    f | front)
        /bin/bash $DGPATH/_scripts/front.sh $2 $3 $4
        break
        ;;
    l | lint)
        cd $DGPATH/../front && pnpm run lint
        break
        ;;
    ck | check)
        cd $DGPATH/../front && pnpm run check
        break
        ;;
    d | docker)
        /bin/bash $DGPATH/_scripts/docker.sh $2 $3
        break
        ;;
    tf | terraform)
        /bin/bash $DGPATH/_scripts/terraform.sh $2 $3 $4 $5 $6
        break
        ;;
    b | bump)
        /bin/bash $DGPATH/_scripts/bump.sh
        break
        ;;
    ch | changelog)
        /bin/bash $DGPATH/_scripts/changelog.sh
        break
        ;;
    g | github)
        open https://github.com/dgrebb/dgrebb.com
        break
        ;;
    gp | github-project)
        open https://github.com/users/dgrebb/projects/12
        break
        ;;
    a | act)
        /bin/bash $DGPATH/_scripts/act.sh $2 $3
        break
        ;;
    tp | test-performance)
        /bin/bash $DGPATH/_scripts/perf.sh $2 $3 $4
        break
        ;;
    tv | test-visual | backstop)
        /bin/bash $DGPATH/_scripts/visual-regression.sh test $2
        break
        ;;
    tvt | test-visual-skip-build | backstop-test)
        /bin/bash $DGPATH/_scripts/visual-regression.sh test-now $2
        break
        ;;
    tvr | test-visual-remote-service | backstop-remote)
        /bin/bash $DGPATH/_scripts/visual-regression.sh remote $2
        break
        ;;
    tvref | test-visual-ref | backstop-reference)
        /bin/bash $DGPATH/_scripts/visual-regression.sh ref $2
        break
        ;;
    tva | test-visual-approve | backstop-approve)
        /bin/bash $DGPATH/_scripts/visual-regression.sh approve $2
        break
        ;;
    sp | spelling | cspell)
        cd $DGPATH/../_ci/spell
        trap exit 0 INT
        /bin/bash $DGPATH/../_ci/spell/content.sh $2
        break
        ;;
    -h | --help)
        showHelp
        break
        ;;
    --)
        showHelp
        break
        ;;
    *)
        projectPath=$(realpath $DGPATH/..)
        if [ $(pwd) = ${projectPath} ]; then
            printDgErr "Unexpected args — you done goofed!" ]
            echo
            showHelp
        else
            printDgMsg "Moving to project directory"
            cd $DGPATH/../
            $SHELL
        fi
        break
        ;;
    esac
done
err=$?
[[ $err != 0 ]] && exit $err
