#!/bin/bash
export directory=$(dirname $(realpath /usr/local/bin/dg))
source $directory/_scripts/functions.sh

showHelp() {
    printf "${NC}$(basename "$0") [-h] [ d db dbl drb drbl r cms tf] -- program to manage dgrebb.com\n
    -h                      show this help text
    d | dev                 run strapi in development mode outside of docker
    db | dbuild             build docker images for aws
    dbl | dbuildlocal       build docker images to run locally
    drb | drebuild          rebuild docker images for aws
    drbl                    rebuild docker images to run locally
    dp                      push docker image
    r | run                 run local docker image
    cms                     interact with strapi sans docker
        dev                 run strapi in development mode
    tf                      run terraform commands
        i | init            initialize terraform
        iu | init-upgrade   upgrade terraform
        p | plan            plan terraform
        a | apply           apply terraform
    \n\n"
}

hello

while test "$1" != --; do
    case $1 in
    c | cms)
        /bin/bash $directory/_scripts/cms.sh $2
        break
        ;;
    f | front)
        /bin/bash $directory/_scripts/front.sh $2
        break
        ;;
    d | docker)
        /bin/bash $directory/_scripts/docker.sh $2 $3
        break
        ;;
    tf | terraform)
        /bin/bash $directory/_scripts/terraform.sh $2 $3
        break
        ;;
    ch | changelog)
        config="_utils/_cliff/all.toml"
        file="CHANGELOG.md"
        cd ${directory}/../ && git cliff -c $config -o ${file}
        echo "Project Changelog Written to ${file}"
        for D in *; do
            if [ -d "${D}" ]; then
                config="_utils/_cliff/dir.toml"
                if [[ "$D" == *"tf"* || "$D" == *"utils"* ]]; then
                    cd ${directory}/../ &&
                        git cliff -c $config \
                            --include-path "${D}/*" \
                            --include-path "${D:1}/*" \
                            -o ./${D}/${file}
                    echo "Changelog for ${D} written to ${D}/${file}"
                else
                    cd ${directory}/../ && git cliff -c $config --include-path "${D}/*" -o ./${D}/${file}
                    echo "Changelog for ${D} written to ${D}/${file}"
                fi
            fi
        done
        break
        ;;
    -h | --help)
        showHelp
        break
        ;;
    --)
        showHelp
        break
        ;;
    *)
        projectPath=$(realpath ${directory}/..)
        if [ $(pwd) = ${projectPath} ]; then
            printDgErr "Unexpected args — you done goofed!" ]
            showHelp
        else
            printDgMsg "Moving to project directory"
            cd ${directory}/../
            $SHELL
        fi
        break
        ;;
    esac
done
err=$?
[[ $err != 0 ]] && exit $err
