variable "domain" {}
variable "cmsdomain" {}
variable "dashed_domain" {}
variable "dashed_cmsdomain" {}
variable "vpc" {}
variable "subnets" {}
variable "cms_cert" {}
variable "cms_validation" {}
variable "lb_sg" {}