name: "✨ Feature"
description: What are we building?
title: "✨ [FEAT] - <title>"
labels:
  [
    "feature",
    "enhancement",
    "frontend",
    "a11y",
    "CMS",
    "ci",
    "testing",
    "refactor",
    "SEO",
  ]
projects: ["dgrebb.com"]
assignees:
  - dgrebb
body:
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this?
      multiple: false
      options:
        - ⦿
        - ⦿ ⦿
        - ⦿ ⦿ ⦿
        - ⦿ ⦿ ⦿ ⦿
        - ⦿ ⦿ ⦿ ⦿ ⦿
      default: 2
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: Provide a brief explanation of the feature
      placeholder: Describe in a few lines your feature request
    validations:
      required: true
  - type: textarea
    id: tasks
    attributes:
      label: Tasks
      description: A few specific words about your feature request.
      value: "- [ ] "
    validations:
      required: false
  - type: input
    id: reprod-url
    attributes:
      label: "URL"
      description: Please enter your GitHub URL to provide a reproduction of the issue
      placeholder: ex. https://github.com/USERNAME/REPO-NAME
    validations:
      required: false