variable "aws_access_key" {}
variable "aws_secret_key" {}
variable "region" {}
variable "domain" {}
variable "subnets" {}
variable "cmsdomain" {}
variable "cdndomain" {}
variable "apidomain" {}
variable "dashed_cmsdomain" {}
variable "cf_distribution" {}
variable "alb" {}
variable "api_gw_domain" {}