variable "aws_access_key" {}
variable "aws_secret_key" {}
variable "region" {}
variable "basedomain" {}
variable "domain" {}
variable "subnets" {}
variable "cmsdomain" {}
variable "cdndomain" {}
variable "dashed_domain" {}
variable "dashed_cmsdomain" {}
variable "www_cdn" {}
variable "uploads_cdn" {}
variable "alb" {}
variable "www_record_overwrite" {}