variable "domain" {}
variable "cdndomain" {}
variable "dashed_domain" {}
variable "bucket" {}
variable "log_enabled" {}
variable "log_bucket" {}
variable "cert" {}
variable "redirect" {}
variable "www" {}
