name: Backstop Remote
run-name: Running Backstop Remote

on:
  workflow_dispatch:

permissions:
  checks: write
  contents: write
  pull-requests: write

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  NODE_VERSION: 20

jobs:
  backstop:
    name: 📱 BackstopJS
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.env }}

    env:
      DEPLOY_ENV: ${{ inputs.env }}

    steps:
      - name: 𐂷 Checkout
        uses: actions/checkout@v4
        with:
          repository: dgrebb/dgrebb.com
          ref: ${{ github.ref }}
          token: ${{ github.token }}
          fetch-depth: 1
          sparse-checkout: |
            .github
            _ci

      # - name: 🛢 Install Dependencies
      #   uses: ./.github/actions/install-cache-deps
      #   with:
      #     WORKSPACE_ROOT: _ci/backstop
      #     BROWSER_BINARIES: true

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: dgrebb/ngrok-ssh@main
        with:
          NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}
          NGROK_CONFIG_FILE: ".github/.config/.ngrok.yml"
      - run: |
          cd _ci/backstop
          npx playwright install
          ENV=$DEPLOY_ENV npm run remote.gh
